### ISSUE TITLE
add a key to run the statement before ;;

### ISSUE THREAD

**Issue by arbipher** [Muchtrix/vscode-tuareg-master#2]
I guess it's common that we want send the statement before ;;

The example is 
`1+2;;`

After typing this, the cursor is after the second ";". If I want to send the statement "1+2", I have to move the cursor left then send it.

Would you please add a key to send the statement before ;; then I don't have to move the cursor left (sorry for my laziness) ?

**Comment by Muchtrix** [comment]
I did a little bit more: from now on, you can send previous statement (from position of the cursor) using ctrl+alt+\
